version = 0.1

[default.deploy.parameters]
stack_name = "teststack"
resolve_s3 = true
s3_prefix = "teststack"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "UniqueKey=\"sdf123\" AOSSCollectionName=\"claim-oss-col\" AOSSIndexName=\"claim-oss-idx\" EmailIdForNotification=\"xxxxx@gmail.com\""
image_repositories = []
